FROM urho3d/dockerized-linux:latest

RUN git clone https://github.com/urho3D/Urho3D.git --depth=1 
RUN cd /Urho3D && /linux_entrypoint.sh rake cmake URHO3D_SAMPLES=0 URHO3D_DEPLOYMENT_TARGET=generic URHO3D_TOOLS=1 URHO3D_HASH_DEBUG=0 URHO3D_PROFILING=0 URHO3D_TESTING=0 
RUN cd /Urho3D/build/dockerized-linux && /linux_entrypoint.sh && make -j $(nproc)


ENV URHO3D_HOME=/Urho3D/build/dockerized-linux
