FROM dertom95/urho3d-arm:latest

RUN cd /Urho3D && git pull origin master && /arm_entrypoint.sh rake cmake URHO3D_SAMPLES=0 URHO3D_TOOLS=0 URHO3D_HASH_DEBUG=0 URHO3D_PROFILING=0 URHO3D_TESTING=0 URHO3D_DEPLOYMENT_TARGET=generic 
RUN cd /Urho3D/build/dockerized-arm && /arm_entrypoint.sh make -j $(nproc)

ADD PackageTool /Urho3D/build/dockerized-arm/bin/tool

