FROM urho3d/dockerized-web:master

RUN git clone https://github.com/urho3D/Urho3D.git --depth=1 
RUN cd /Urho3D && /web_entrypoint.sh rake cmake web URHO3D_SAMPLES=0 URHO3D_TOOLS=0 URHO3D_HASH_DEBUG=0 URHO3D_PROFILING=0 URHO3D_TESTING=0 URHO3D_DEPLOYMENT_TARGET=generic 
RUN cd /Urho3D && /web_entrypoint.sh rake make web -j $(nproc)

ENV URHO3D_HOME=/Urho3D/build/web

ADD PackageTool /Urho3D/build/web/bin/tool

# build once the minimal-project in order to create the emcc system library (otherwise thise would be done on every compile afterwards)
RUN git clone https://github.com/dertom95/urho3d-minimal-new-project.git tempProject
RUN cd /tempProject && rake cmake web
RUN cd /tempProject && rake make web -j $(nproc)
RUN rm -Rf /tempProject
