FROM urho3d/dockerized-native:latest

RUN git clone https://github.com/urho3D/Urho3D.git --depth=1 
RUN cd /Urho3D && /native_entrypoint.sh rake cmake URHO3D_SAMPLES=0 URHO3D_TOOLS=1 URHO3D_HASH_DEBUG=0 URHO3D_PROFILING=0 URHO3D_TESTING=0 
RUN cd /Urho3D && /native_entrypoint.sh rake make -j $(nproc)


ENV URHO3D_HOME=/Urho3D/build/native
